[package]
rust-version.workspace = true
name = "sdkwork-api-forum-standalone-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "sdkwork-api-forum-standalone-gateway"
path = "src/main.rs"


[lints]
workspace = true
[dependencies]
sdkwork-api-forum-assembly = { workspace = true }
sdkwork-database-ops-http = { workspace = true }
sdkwork-iam-web-adapter = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
sdkwork-web-bootstrap = { workspace = true }
