[package]
rust-version.workspace = true
name = "sdkwork-forum-service-host"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true


[lints]
workspace = true
[dependencies]
sdkwork-communication-forum-repository-sqlx = { workspace = true }
sdkwork-communication-forum-service = { workspace = true }
sdkwork-forum-database-host = { workspace = true }
sdkwork-database-config = { workspace = true }
sdkwork-database-sqlx = { workspace = true }
sdkwork-database-spi = { workspace = true }
sdkwork-database-ops = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
dotenvy = "0.15"

[lib]
path = "src/lib.rs"
